import "./globals.scss";
import { Inter } from "next/font/google";
import { Navigation } from "@/components/navigation";
import { ApolloWrapperClient } from "../lib/apollo.client";

const inter = Inter({ subsets: ["latin"] }); // Load Inter font

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ApolloWrapperClient>
          <Navigation />
          {children}
        </ApolloWrapperClient>
      </body>
    </html>
  );
}
